SELECT R.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    M.FAVORITES
FROM REST_INFO R
JOIN (SELECT MAX(FAVORITES) AS FAVORITES,
    FOOD_TYPE
FROM REST_INFO
GROUP BY FOOD_TYPE) M
ON R.FAVORITES = M.FAVORITES
AND R.FOOD_TYPE = M.FOOD_TYPE
ORDER BY FOOD_TYPE DESC
;