-- 코드를 입력하세요
SELECT I.FOOD_TYPE,
    I.REST_ID,
    I.REST_NAME,
    I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT MAX(FAVORITES) AS FAVORITES,
    FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) M
ON I.FAVORITES = M.FAVORITES
AND I.FOOD_TYPE = M.FOOD_TYPE
ORDER BY FOOD_TYPE DESC
;