SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO F
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAXLENG
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
ON F.FISH_TYPE = M.FISH_TYPE
AND F.LENGTH = M.MAXLENG
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = F.FISH_TYPE
ORDER BY F.ID